export const products_row_one = [
    {
        id: 1,
        category: "clásicos",
        title: "80's Socks",
        description: "Medias retro, estilo de los 80's",
        price: 35.00,
        image: "/imagen/80socks.jpeg",
    },
    {
        id: 2,
        category: "clásicos",
        title: "Green Socks",
        description: "Color verde intenso, con franjas blancas. Estilo muy clásico",
        price: 35.00,
        image: "/imagen/clasic_green-socks.jpeg",
    },
    {
        id: 3,
        category: "clásicos",
        title: "Bicolor Socks",
        description: "Medias blancas con franjas gruesas, rojo y azul.",
        price: 40.00,
        image: "/imagen/retro-socks.jpeg",
    },
    {
        id: 4,
        category: "colores",
        title: "Brown Socks",
        description: "De color marron claro, textura suave y comoda.",
        price: 25.00,
        image: "/imagen/brown-socks.jpeg",
    },
    {
        id: 5,
        category: "colores",
        title: "Green Socks",
        description: "Verdes son franjas blancas delgadas.",
        price: 25.00,
        image: "/imagen/green-socks.jpeg",
    },
    {
        id: 6,
        category: "colores",
        title: "White Socks",
        description: "Clasicas blancas con texto vertical.",
        price: 28.00,
        image: "/imagen/white-socks.jpeg",
    },
    {
        id: 7,
        category: "colores",
        title: "Yellow Socks",
        description: "Amarillo pastel, con texto azul",
        price: 28.00,
        image: "/imagen/yellow-socks.jpeg",
    },
    {
        id: 8,
        category: "caricaturas",
        title: "Calamardo Socks",
        description: "Calamardo con las manos en la cintura y mirada seria.",
        price: 35.00,
        image: "/imagen/calamardo-socks.jpeg",
    },
    {
        id: 9,
        category: "caricaturas",
        title: "Charlie Brown",
        description: "Charlie Brown en fondo blanco",
        price: 35.00,
        image: "/imagen/charlie-socks.jpeg",
    },
    {
        id: 10,
        category: "random",
        title: "Sockete",
        description: "Nuestro Sockete en fondo celeste",
        price: 35.00,
        image: "/imagen/sockete-socks.jpeg",
    },
    {
        id: 11,
        category: "random",
        title: "'Happy' Face",
        description: "Rostro feliz en fondo púrpura",
        price: 35.00,
        image: "/imagen/purple_face-socks.jpeg",
    },
    {
        id: 12,
        category: "random",
        title: "Zombie Socks",
        description: "Pies de zombie",
        price: 35.00,
        image: "/imagen/random-socks.jpeg",
    },
]